title: Зөв бичигдэв
description: Монгол үгийн алдаа шалгах толь
remote_theme: rundocs/jekyll-rtd-theme
url: "https://zuv.bichig.dev"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
meta:
  yandex-verification: 34a56b64aa11897a
tags: [монгол үсгийн дүрэм, ц. дамдинсүрэнгийн үсгийн дүрэм, монгол үсгийн дүрмийн толь татах, монгол үсгийн дүрмийн алдаа шалгах толь, монгол үгийн алдаа шалгах толь, зөв бичигдэв, zuv bichig dev, zuv bichigdev, mongolian spelling checker, emacs, firefox, adobe indesign, libreoffice, seamonkey, sublime text, texmaker, texstudio, thunderbird, монгол үгийн алдаа шалгах цахим толь, алдаа шалгагч, алдаа шалгагч программ, алдаа шалгагч программ татах, алдаа шалгагч программ, алдаа шалгагч программ татах, aldaa shalgagch, aldaa shalgah, aлдаа шалгагч, mongolian spell check, үсгийн алдаа шалгагч, үсгийн алдаа шалгах, Монгол хэлний зөв бичих дүрэм, зөв бичих дүрэм, зөв бичгийн дүрэм]
tag_page_layout: tag_page
tag_page_dir: tag
